### ISSUE TITLE
QuickLook.Common not found

### ISSUE THREAD

**Issue by LinTeX9527** [zhangkaihua88/QuickLook.Plugin.JupyterNotebookViewer#2]
vs2022 加载最新的工程，出现如下问题：找不到 QuickLook.Common 工程
![图片](https://user-images.githubusercontent.com/10264703/226814760-fe284cf3-7c4c-4a1a-9955-d10ee60e662a.png)

**Comment by zhangkaihua88** [comment]
可以在这里下载，加载进去，因为存在官方版本，所以没有上传。https://github.com/QL-Win/QuickLook.Common
